<a href="https://colab.research.google.com/github/dwighto/courses/blob/master/notebooks/12_Edades_MetaCortex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cálculo de edades en un dataframe

In [1]:
import numpy as np
import pandas as pd
from datetime import datetime, date

In [2]:
!git clone https://github.com/franciscogarate/cdiae

Cloning into 'cdiae'...
remote: Enumerating objects: 305, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 305 (delta 73), reused 49 (delta 38), pack-reused 200 (from 1)
Receiving objects: 100% (305/305), 5.16 MiB | 18.62 MiB/s, done.
Resolving deltas: 100% (160/160), done.

In [3]:
df = pd.read_feather('cdiae/data/03_model_input/empleados_metacortex_clean.ftr')
df.head()

  IdAsegurado     FNacim      FAlta Sexo  Activo     CP  Capital
0   88862218Q 1990-01-15 2020-01-15    F    True  28013   5000.0
1   17905733A 1985-12-03 2019-12-03    M    True  41001   6500.0
3   52745245N 1992-07-22 2021-07-22    F   False  48004   3000.0
4   82167366G 1988-04-10 2018-04-10    M    True  48001   5000.0
5    1248870G 1981-03-11 2018-04-10    M    True  48007   6000.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 8
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   IdAsegurado  7 non-null      object
 1   FNacim       7 non-null      datetime64[ns]
 2   FAlta        7 non-null      datetime64[ns]
 3   Sexo         7 non-null      object
 4   Activo       7 non-null      bool
 5   CP           7 non-null      int64
 6   Capital      7 non-null      float64
dtypes: bool(1), datetime64[ns](2), float64(1), int64(1), object(2)
memory usage: 399.0+ bytes

In [7]:
fval = pd.to_datetime('2024-12-31')

In [9]:
def EdAct(fechanac, fval):
    if not isinstance(fechanac, datetime):
        fechanac = pd.to_datetime(str(fechanac))
    if not isinstance(fval, datetime):
        fval = pd.to_datetime(str(fval))

    return round((fval - fechanac).days / 365.2425)

In [10]:
df['edad_actuarial'] = df['FNacim'].apply(lambda x: EdAct(x, fval))
df.head()

,IdAsegurado,FNacim,FAlta,Sexo,Activo,CP,Capital,edad_actuarial
0,88862218Q,1990-01-15,2020-01-15,F,True,28013,5000.0,35
1,17905733A,1985-12-03,2019-12-03,M,True,41001,6500.0,39
3,52745245N,1992-07-22,2021-07-22,F,False,48004,3000.0,32
4,82167366G,1988-04-10,2018-04-10,M,True,48001,5000.0,37
5,1248870G,1981-03-11,2018-04-10,M,True,48007,6000.0,44

In [11]:
def EdCumplida(fechanac, fval):
	if not isinstance(fechanac, datetime):
		fechanac = pd.to_datetime(str(fechanac))
	if not isinstance(fval, datetime):
		fval = pd.to_datetime(str(fval))

	edad = fval.year - fechanac.year - ((fval.month, fval.day) < (fechanac.month, fechanac.day))
	return np.maximum(edad, 0)

In [12]:
df['edad_cumplida'] = df['FNacim'].apply(lambda x: EdCumplida(x, fval))
df.head()

,IdAsegurado,FNacim,FAlta,Sexo,Activo,CP,Capital,edad_actuarial,edad_cumplida
0,88862218Q,1990-01-15,2020-01-15,F,True,28013,5000.0,35,34
1,17905733A,1985-12-03,2019-12-03,M,True,41001,6500.0,39,39
3,52745245N,1992-07-22,2021-07-22,F,False,48004,3000.0,32,32
4,82167366G,1988-04-10,2018-04-10,M,True,48001,5000.0,37,36
5,1248870G,1981-03-11,2018-04-10,M,True,48007,6000.0,44,43